load("@rules_java//java:defs.bzl", "java_binary", "java_library", "java_test")
load("@rules_rhino//java:defs.bzl", "java_test_suite", "junit5_test", "google_java_format_check", "google_java_format_fix")
load("@rules_rhino//babel:defs.bzl", "babel_preprocess", "npm_install")
load("//bazel:file_list.bzl", "file_list")

npm_install(
    name = "babel_deps",
    package_json = "//bazel:package.json",
    package_lock = "//bazel:package-lock.json",
)

babel_preprocess(
    name = "preprocessed_node_lib",
    srcs = glob(
        ["node/lib/**/*.js"],
        # Locally-modified files
        exclude = [
            "node/lib/internal/errors.js",
            "node/lib/internal/per_context/primordials.js",
            "node/lib/internal/test_runner/reporter/tap.js",
        ],
    ) + glob(["nodejs-local/**/*.js"]) + ["node/deps/minimatch/index.js"],
    prefix = "nodejs",
    config = "//bazel:babel.config.json",
    npm = ":babel_deps",
)

java_library(
    name = "ithaca",
    srcs = glob(
        ["src/main/java/**"],
        exclude = ["src/main/java/org/brail/ithaca/Main.java"],
    ),
    resources =
        [
            ":internal_modules",
            ":preprocessed_node_lib",
        ] + glob([
            "src/main/resources/**",
        ]),
    deps = [
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:com_fasterxml_jackson_core_jackson_core",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_github_teaconmc_urlpattern",
        "@maven//:org_slf4j_slf4j_api",
        "@rhino//rhino",
    ],
)

java_binary(
    name = "ithaca-cli",
    srcs = ["src/main/java/org/brail/ithaca/Main.java"],
    main_class = "org.brail.ithaca.Main",
    runtime_deps = ["@maven//:org_slf4j_slf4j_simple"],
    deps = [
        ":ithaca",
        "@maven//:org_slf4j_slf4j_api",
        "@rhino//rhino",
    ],
)

# Make a file containing a list of preprocessed filenames.
# We need this because Node likes to get a big array of the names
# of the internal modules.
file_list(
    name = "internal_modules",
    srcs = [
        ":preprocessed_node_lib",
    ],
    strip_prefix = "nodejs",
    strip_suffix = ".js",
)

java_test_suite(
    name = "unittests",
    size = "small",
    srcs = glob(
        ["src/test/java/org/brail/ithaca/internal/**/*.java"],
    ),
    runtime_deps = ["@maven//:org_slf4j_slf4j_simple"],
    deps = [
        ":ithaca",
        "@maven//:org_junit_jupiter_junit_jupiter",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@rhino//rhino",
    ],
)

java_library(
    name = "integration_lib",
    srcs = glob(
        ["src/test/java/org/brail/ithaca/integration/**/*.java"],
        exclude = ["src/test/java/org/brail/ithaca/integration/**/*Test.java"],
    ),
    deps = [
        ":ithaca",
        "@bazel_tools//tools/java/runfiles",
        "@maven//:org_junit_jupiter_junit_jupiter",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@rhino//rhino",
    ],
)

java_test_suite(
    name = "integrationtests",
    size = "small",
    srcs = glob(
        ["src/test/java/org/brail/ithaca/integration/**/*Test.java"],
    ),
    data = glob([
        "tests/**/*.js",
        "tests/**/*.json",
    ]),
    runtime_deps = ["@maven//:org_slf4j_slf4j_simple"],
    deps = [
        ":integration_lib",
        ":ithaca",
        "@bazel_tools//tools/java/runfiles",
        "@maven//:org_junit_jupiter_junit_jupiter",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@rhino//rhino",
    ],
)

babel_preprocess(
    name = "preprocessed_tests",
    srcs = glob(
        [
            "node/test/common/**/*.js",
            "node/test/sequential/*.js",
        ],
    ) + glob(["nodejs-local/**/*.js"]) + ["node/deps/minimatch/index.js"],
    prefix = "nodetest",
    config = "//bazel:babel.config.json",
    npm = ":babel_deps",
)

google_java_format_check(
    name = "check_format",
    files = glob(["**/*.java"]),
    tags = ["manual"],
)

google_java_format_fix(
    name = "fix_format",
)