'use strict';

function _classCallCheck(a, n) { if (!(a instanceof n)) throw new TypeError("Cannot call a class as a function"); }
function _defineProperties(e, r) { for (var t = 0; t < r.length; t++) { var o = r[t]; o.enumerable = o.enumerable || !1, o.configurable = !0, "value" in o && (o.writable = !0), Object.defineProperty(e, _toPropertyKey(o.key), o); } }
function _createClass(e, r, t) { return r && _defineProperties(e.prototype, r), t && _defineProperties(e, t), Object.defineProperty(e, "prototype", { writable: !1 }), e; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == typeof i ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != typeof t || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != typeof i) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); }
var {
  ArrayPrototypeJoin,
  ArrayPrototypeMap,
  ArrayPrototypeSlice,
  ArrayPrototypeSort,
  JSONStringify,
  ObjectKeys,
  SafeMap,
  String: _String,
  StringPrototypeReplaceAll,
  StringPrototypeSlice
} = primordials;
var {
  codes: {
    ERR_INVALID_STATE
  }
} = require('internal/errors');
var {
  kEmptyObject
} = require('internal/util');
var debug = require('internal/util/debuglog').debuglog('test_runner', fn => {
  debug = fn;
});
var {
  validateArray,
  validateFunction,
  validateObject,
  validateString
} = require('internal/validators');
var {
  strictEqual
} = require('assert');
var {
  mkdirSync,
  readFileSync,
  writeFileSync
} = require('fs');
var {
  dirname
} = require('path');
var {
  createContext,
  runInContext
} = require('vm');
var kMissingSnapshotTip = 'Missing snapshots can be generated by rerunning ' + 'the command with the --test-update-snapshots flag.';
var defaultSerializers = [value => {
  return JSONStringify(value, null, 2);
}];
function defaultResolveSnapshotPath(testPath) {
  if (typeof testPath !== 'string') {
    return testPath;
  }
  return `${testPath}.snapshot`;
}
var resolveSnapshotPathFn = defaultResolveSnapshotPath;
var serializerFns = defaultSerializers;
function setResolveSnapshotPath(fn) {
  validateFunction(fn, 'fn');
  resolveSnapshotPathFn = fn;
}
function setDefaultSnapshotSerializers(serializers) {
  validateFunctionArray(serializers, 'serializers');
  serializerFns = ArrayPrototypeSlice(serializers);
}
var SnapshotFile = /*#__PURE__*/function () {
  function SnapshotFile(snapshotFile) {
    _classCallCheck(this, SnapshotFile);
    this.snapshotFile = snapshotFile;
    this.snapshots = {
      __proto__: null
    };
    this.nameCounts = new SafeMap();
    this.loaded = false;
  }
  return _createClass(SnapshotFile, [{
    key: "getSnapshot",
    value: function getSnapshot(id) {
      if (!(id in this.snapshots)) {
        var err = new ERR_INVALID_STATE(`Snapshot '${id}' not found in ` + `'${this.snapshotFile}.' ${kMissingSnapshotTip}`);
        err.snapshot = id;
        err.filename = this.snapshotFile;
        throw err;
      }
      return this.snapshots[id];
    }
  }, {
    key: "setSnapshot",
    value: function setSnapshot(id, value) {
      this.snapshots[escapeSnapshotKey(id)] = value;
    }
  }, {
    key: "nextId",
    value: function nextId(name) {
      var count = this.nameCounts.get(name) ?? 1;
      this.nameCounts.set(name, count + 1);
      return `${name} ${count}`;
    }
  }, {
    key: "readFile",
    value: function readFile() {
      if (this.loaded) {
        debug('skipping read of snapshot file');
        return;
      }
      try {
        var source = readFileSync(this.snapshotFile, 'utf8');
        var context = {
          __proto__: null,
          exports: {
            __proto__: null
          }
        };
        createContext(context);
        runInContext(source, context);
        if (context.exports === null || typeof context.exports !== 'object') {
          throw new ERR_INVALID_STATE(`Malformed snapshot file '${this.snapshotFile}'.`);
        }
        for (var key in context.exports) {
          this.snapshots[key] = templateEscape(context.exports[key]);
        }
        this.loaded = true;
      } catch (err) {
        throwReadError(err, this.snapshotFile);
      }
    }
  }, {
    key: "writeFile",
    value: function writeFile() {
      try {
        var keys = ArrayPrototypeSort(ObjectKeys(this.snapshots));
        var snapshotStrings = ArrayPrototypeMap(keys, key => {
          return `exports[\`${key}\`] = \`${this.snapshots[key]}\`;\n`;
        });
        var output = ArrayPrototypeJoin(snapshotStrings, '\n');
        mkdirSync(dirname(this.snapshotFile), {
          __proto__: null,
          recursive: true
        });
        writeFileSync(this.snapshotFile, output, 'utf8');
      } catch (err) {
        throwWriteError(err, this.snapshotFile);
      }
    }
  }]);
}();
var SnapshotManager = /*#__PURE__*/function () {
  function SnapshotManager(updateSnapshots) {
    _classCallCheck(this, SnapshotManager);
    // A manager instance will only read or write snapshot files based on the
    // updateSnapshots argument.
    this.updateSnapshots = updateSnapshots;
    this.cache = new SafeMap();
  }
  return _createClass(SnapshotManager, [{
    key: "resolveSnapshotFile",
    value: function resolveSnapshotFile(entryFile) {
      var snapshotFile = this.cache.get(entryFile);
      if (snapshotFile === undefined) {
        var resolved = resolveSnapshotPathFn(entryFile);
        if (typeof resolved !== 'string') {
          var err = new ERR_INVALID_STATE('Invalid snapshot filename.');
          err.filename = resolved;
          throw err;
        }
        snapshotFile = new SnapshotFile(resolved);
        snapshotFile.loaded = this.updateSnapshots;
        this.cache.set(entryFile, snapshotFile);
      }
      return snapshotFile;
    }
  }, {
    key: "serialize",
    value: function serialize(input) {
      var serializers = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : serializerFns;
      try {
        var value = serializeValue(input, serializers);
        return `\n${templateEscape(value)}\n`;
      } catch (err) {
        throwSerializationError(input, err);
      }
    }
  }, {
    key: "serializeWithoutEscape",
    value: function serializeWithoutEscape(input) {
      var serializers = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : serializerFns;
      try {
        return serializeValue(input, serializers);
      } catch (err) {
        throwSerializationError(input, err);
      }
    }
  }, {
    key: "writeSnapshotFiles",
    value: function writeSnapshotFiles() {
      if (!this.updateSnapshots) {
        debug('skipping write of snapshot files');
        return;
      }
      this.cache.forEach(snapshotFile => {
        snapshotFile.writeFile();
      });
    }
  }, {
    key: "createAssert",
    value: function createAssert() {
      var manager = this;
      return function snapshotAssertion(actual) {
        var options = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : kEmptyObject;
        validateObject(options, 'options');
        var {
          serializers = serializerFns
        } = options;
        validateFunctionArray(serializers, 'options.serializers');
        var {
          filePath,
          fullName
        } = this;
        var snapshotFile = manager.resolveSnapshotFile(filePath);
        var value = manager.serialize(actual, serializers);
        var id = snapshotFile.nextId(fullName);
        if (manager.updateSnapshots) {
          snapshotFile.setSnapshot(id, value);
        } else {
          snapshotFile.readFile();
          strictEqual(value, snapshotFile.getSnapshot(id));
        }
      };
    }
  }, {
    key: "createFileAssert",
    value: function createFileAssert() {
      var manager = this;
      return function fileSnapshotAssertion(actual, path) {
        var options = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : kEmptyObject;
        validateString(path, 'path');
        validateObject(options, 'options');
        var {
          serializers = serializerFns
        } = options;
        validateFunctionArray(serializers, 'options.serializers');
        var value = manager.serializeWithoutEscape(actual, serializers);
        if (manager.updateSnapshots) {
          try {
            mkdirSync(dirname(path), {
              __proto__: null,
              recursive: true
            });
            writeFileSync(path, value, 'utf8');
          } catch (err) {
            throwWriteError(err, path);
          }
        } else {
          var expected;
          try {
            expected = readFileSync(path, 'utf8');
          } catch (err) {
            throwReadError(err, path);
          }
          strictEqual(value, expected);
        }
      };
    }
  }]);
}();
function throwReadError(err, filename) {
  var msg = `Cannot read snapshot file '${filename}.'`;
  if (err?.code === 'ENOENT') {
    msg += ` ${kMissingSnapshotTip}`;
  }
  var error = new ERR_INVALID_STATE(msg);
  error.cause = err;
  error.filename = filename;
  throw error;
}
function throwWriteError(err, filename) {
  var msg = `Cannot write snapshot file '${filename}.'`;
  var error = new ERR_INVALID_STATE(msg);
  error.cause = err;
  error.filename = filename;
  throw error;
}
function throwSerializationError(input, err) {
  var error = new ERR_INVALID_STATE('The provided serializers did not generate a string.');
  error.input = input;
  error.cause = err;
  throw error;
}
function serializeValue(value, serializers) {
  var v = value;
  for (var i = 0; i < serializers.length; ++i) {
    var fn = serializers[i];
    v = fn(v);
  }
  return v;
}
function validateFunctionArray(fns, name) {
  validateArray(fns, name);
  for (var i = 0; i < fns.length; ++i) {
    validateFunction(fns[i], `${name}[${i}]`);
  }
}
function escapeSnapshotKey(str) {
  var result = StringPrototypeSlice(JSONStringify(str, null, 2), 1, -1);
  result = StringPrototypeReplaceAll(result, '`', '\\`');
  result = StringPrototypeReplaceAll(result, '${', '\\${');
  return result;
}
function templateEscape(str) {
  var result = _String(str);
  result = StringPrototypeReplaceAll(result, '\\', '\\\\');
  result = StringPrototypeReplaceAll(result, '`', '\\`');
  result = StringPrototypeReplaceAll(result, '${', '\\${');
  return result;
}
module.exports = {
  SnapshotManager,
  defaultResolveSnapshotPath,
  // Exported for testing only.
  defaultSerializers,
  // Exported for testing only.
  setDefaultSnapshotSerializers,
  setResolveSnapshotPath
};

